#ifndef _FOC_PROTOCOL_ENDPOINTS_ENUM_H
#define _FOC_PROTOCOL_ENDPOINTS_ENUM_H

#include "stdint.h"
#include "stddef.h"

typedef enum PROTOCOL_ENDPOINT
{
    NODE_ID = 0,
    CONFIGURATION, // Writeonly
    VBUS,
    IBUS,
    POWER,
    SERIAL_NUMBER,
    DRIVE_ERROR_CODE,
    OUTPUT_STATE,
    DRIVE_MODE,
    CURRENT_PHASE_A,
    CURRENT_PHASE_B,
    CURRENT_PHASE_C,
    CURRENT_IALPHA,
    CURRENT_IBETA,
    CURRENT_IQ,
    CURRENT_ID,
    VQ_OUT,
    VD_OUT,
    VALPHA_OUT,
    VBETA_OUT,
    COMPARE_A,
    COMPARE_B,
    COMPARE_C,
    IQ_TARGET, // R/W
    ID_TARGET,
    IQ_SET,    // R
    ID_SET,
    SPEED_TARGET,
    POS_ABS_SET_RAD,
    POS_INC_RAD,
    POS_ABS_SET_DEG,
    POS_INC_DEG,
    CURRENT_KP,
    CURRENT_KI,
    VPHASE_LIMIT,
    CURRENT_RAMP_LIMIT,
    SPEED_KP,
    SPEED_KI,
    SPEED_KD,
    SPEED_CURRENT_LIMIT,
    SPEED_RAMP_LIMIT,
    POS_KP,
    POS_KI,
    POS_KD,
    POS_SPEED_LIMIT,
    POS_RAMP_LIMIT,
    ELECTRIC_ANGLE_RAD,
    ELECTRIC_ANGLE_DEG,
    ESTIMATED_ANGLE_RAD,
    ESTIMATED_ANGLE_DEG,
    ESTIMATED_RAW_ANGLE_RAD,
    ESTIMATED_RAW_ANGLE_DEG,
    ESTIMATED_SPEED, // RPM
    ESTIMATED_ACCELERATION,
    GO_HOME,
    BREAK_MODE,

    TRAJ_POS_STATE,  // Readonly
    TRAJ_TARGET_RAD, // R/W, trigger traj
    TRAJ_TARGET_DEG,
    TRAJ_TARGET_INC_RAD, // Writeonly
    TRAJ_TARGET_INC_DEG,
    TRAJ_CRUISE_SPEED,
    TRAJ_MAX_ACCEL,
    TRAJ_MAX_DECEL,
    TRAJ_CURRENT_POS,
    TRAJ_CURRENT_SPEED,
    TRAJ_CURRENT_ACCEL,

    MCU_TEMP,
    MOTOR_TEMP,
    MOSFET_TEMP,
    
    SET_HOME, // Writeonly
    HAS_SET_HOME, // Readonly
    INDICATOR_STATE,  // Writeonly
    INDICATOR_TOGGLE, // Writeonly
    MECHANIC_SPEED_LIMIT,
    LAST_EP_PLACEHOLDER // For auto-detect endpoints count
}PROTOCOL_ENDPOINT;

#endif